# -*- coding: utf-8 -*-
"""belajar 31 maret 2026

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f6fNtCJCzZucvfrm3v5emZIAaVCNCZ7i

**MEMERIKSA JENIS TIPE DATA**
"""

nama = "surya kencana"
usia = 30
single = True

print(type(nama))
print(type(usia))
print(type(single))

usia = input("masukkan usia anda")

"""**KONVERSI TIPE DATA**"""

panjang = input("masukkan panjang : ")
lebar = input("masukkan lebar : ")
tinggi = input("masukkan tinggi : ")

"""**KONVERSI DATA SECARA IMPLISIT**"""

a = 8/2
print(type(a))

b = 4/2
print(type(b))

kata = "semangka"

print(kata)

"""**KONVERSI STRING KE NUMERIK**"""

panjang = int(input("masukkan panjang : "))
lebar = int(input("masukkan lebar : "))
tinggi = int(input("masukkan tinggi : "))

print("luas =", panjang * lebar)

nama = 'aron'
tahun_lahir = 2006

print(nama + 'lahir pada tahun' + str(tahun_lahir))