# -*- coding: utf-8 -*-
"""tugas compro 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DdNmZEsVjhhk1DYhr211Wgb-Fo3AycpW

manipulasi string 2
"""

berita = 'Ramai-ramai developer di seluruh dunia mulai menggunakan \
teks editor masa kini seperti visual Studio Code,\
atom, sublime text, dan lain sebagainya.'


print('sublime text' in berita) # output:True
print('notepadd++'in berita) # output: False

"""**slicing string**



"""

judul = 'Pelajaran Matematika Untuk SD'

print(judul[0:5]) # output:pelaj
print(judul[:10]) # output:pelajaran
print(judul[10:15]) # output:matem
print(judul[-1:-3]) # output:
print(judul[:-3]) # output:Pelajaran Matematika Untuk
print(judul[-5:]) # output:uK SD

"""**menghitung panjang string**"""

print(len('Indonesia'))
print(len('Malaysia'))

"""**memotong string**"""

nama = 'Lendis Fabri'
print(nama[4])
print(nama[7])
print(nama[-1])
print(nama[-3])

"""memeriksa karakter awal string

sring.startswith()
"""

nomor_telepon_1 = '0871122334455'
nomor_telepon_2 = '62887766555300'
nomor_telepon_3 = '+6233003300330'

kode_negara = '+62'
print(nomor_telepon_1.startswith(kode_negara)) # False
print(nomor_telepon_2.startswith(kode_negara)) # False
print(nomor_telepon_3.startswith(kode_negara)) # True

"""**memeriksa karakter akhir string**"""

email_1 = 'aronsitopu@gmail.com'
email_2 = 'aronsitopu@outlook.com'

print(email_1.endswith('@gmail.com')) # True
print(email_2.endswith('@gmail.com')) # False